import type { NextPage } from "next"
import Head from "next/head"

const Home: NextPage = () => {
  return (
    <div className="grid mt-32 place-items-center space-y-4">
      <Head>
        <title>Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-6xl font-bold">Hello from Next.js!</h1>
      <h2>Next.js, TypeScript and Tailwind.</h2>
        <a
          href="https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fdevelopedbytoby%2Fnextjs-typescript-tailwind-starter"
        >
          <img 
            src="https://vercel.com/button" 
            alt="Deploy with Vercel"
          />
        </a>
    </div>
  )
}

export default Home
